ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_provider_fk
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_patient_fk
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE RADIOLOGYTREATMENT DROP CONSTRAINT FK_RADIOLOGYTREATMENT_ID
ALTER TABLE SURGERYTREATMENT DROP CONSTRAINT FK_SURGERYTREATMENT_ID
ALTER TABLE RADIOLOGISTPROVIDER DROP CONSTRAINT FK_RADIOLOGISTPROVIDER_ID
ALTER TABLE PHYSICIANPROVIDER DROP CONSTRAINT FK_PHYSICIANPROVIDER_ID
ALTER TABLE SURGEONPROVIDER DROP CONSTRAINT FK_SURGEONPROVIDER_ID
DROP TABLE TREATMENT CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE PATIENT CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE RADIOLOGYTREATMENT CASCADE
DROP TABLE SURGERYTREATMENT CASCADE
DROP TABLE RADIOLOGISTPROVIDER CASCADE
DROP TABLE PHYSICIANPROVIDER CASCADE
DROP TABLE SURGEONPROVIDER CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
